<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PinEvent extends Model
{

    protected $table = "pin_event";
    protected $primaryKey = "pin_id";
    public static function createNewPin($post_id,$user_id){
        $pin = new PinEvent();
        $pin["post_id"]=$post_id;
        $pin["user_id"]=$user_id;
        $pin->save();
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        PinEvent::observe(new NotificationObserver());
    }
}
